### ISSUE TITLE
Modificar FlatterUser para gestión de propiedades favoritas

### ISSUE THREAD

**Issue by Alex-GF** [ISPP-G10/flatter#192]
Se deben modificar el siguiente modelo:

- FlatterUser (módulo authentication): Añadir una relación ManyToMany con properties denominada `favourite_properties`

**Comment by CarlosNuchera** [comment]
La relación ya está creada en Properties dentro de mainApp

**Comment by CarlosNuchera** [comment]
La he sustituido por la propiedad interested_users para evitar conflictos por circularidad dentro de la entidad property
